return {
  angularls = {},
  astro = {},
  -- biome = {},
  cssmodules_ls = {},
  --custom_elements_ls = {},
  emmet_ls = {},
  eslint = {},
  graphql = {},
  prismals = {},
  svelte = {},
  tailwindcss = {},
  ts_ls = {},
  volar = {},
  vtsls = {},
  vuels = {},
}
